[package]
name = "repolog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
regex = "1.10.5"
serde = { version = "1.0.204", features = ["derive"] }
walkdir = "2.5.0"
